[package]
edition = "2021"
name = "zero2prod"
version = "0.1.0"

[dependencies]
actix-web = "*"
chrono = "*"
config = "0.11"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.1"
secrecy = { version = "0.8.0", features = ["serde"] }
uuid = { version = "*", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.5.7", features = ["runtime-actix-rustls", "macros", "postgres", "uuid", "chrono", "migrate", "offline"], default-features = false }
tokio = { version = "*", features = ["rt-multi-thread", "macros"] }
tracing-actix-web = "0.5"

[dev-dependencies]
reqwest = "*"
once_cell = "1"

[target]
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=lld"]
